title: "Admin's Intimacy"
subtitle: "$ ssh soulmate@lover -i ~/.ssh/trust"
author: sealeelike
year: 2025

description: "A Deep Dive with AI into Love, Sex, and Connection"

theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag
  
copyright: "© 2025 sealeelike. Licensed under CC BY-NC-ND 4.0."

collections:
  chapters:
    output: true
    permalink: /:collection/:name
